### ISSUE TITLE
Git

### ISSUE THREAD

**Issue by elizabethmcd** [ComBEE-UW-Madison/2017-09-29-git-workshop#1]
Plan lessons for Git in shell and clicking in Github

**Comment by sstevens2** [comment]
Can I request you are more specific on this issue?  I'm not sure what you are talking about here.

**Comment by elizabethmcd** [comment]
Figure out what we want to keep/take from SWC git-novice. I particularly just want to spend time on local git, clicking in Github, and how you use that for your own workflow. I would be fine with skipping collaborating and conflicts. We also have to plan what we want them to have setup beforehand in terms of installations. Such as github account, linking it to the computer. I think we might have to walk through that as well

**Comment by sstevens2** [comment]
Ahh... Agreed.  Made specific issue for removing collaborating #4.  
~I'll add one for for removing conflicts as well.~ Added now #6 
Can I suggest for this collaboration we stick to PR's? and then review each other's PRs and the other person merges them when we decide they are ready?
Installation instructions are already linked on this page...https://combee-uw-madison.github.io/2017-09-29-git-workshop/setup/
