### ISSUE TITLE
Add lesson on using gh-pages

### ISSUE THREAD

**Issue by elizabethmcd** [ComBEE-UW-Madison/2017-09-29-git-workshop#2]
Plan lessons for teaching Github Pages with Jekyll. Example is [U of T Coders'](https://uoftcoders.github.io/studyGroup/lessons/misc/jekyll-ghpages/lesson/) lesson. Also show them different templates and how forking and changing a few things can get you going quite quickly.

**Comment by sstevens2** [comment]
I see this issue as, add lesson on using gh-pages.

**Comment by elizabethmcd** [comment]
Yeah it wasn't specific. Basically just use UofT as a starter point, and to walk through other templates I guess.

**Comment by elizabethmcd** [comment]
Basically what are the most important things for spinning up any template through GH-pages

**Comment by sstevens2** [comment]
Off the top of my head, I think the things that need to be included in the gh-page lesson are:
- Finding a template
- Setting up your version of the template
- Modifying the template
- Serving locally to check revisions

**Comment by elizabethmcd** [comment]
I've done this in the intro and personalize lessons
