### ISSUE TITLE
Remove using git from Rstudio lesson

### ISSUE THREAD

**Issue by sstevens2** [ComBEE-UW-Madison/2017-09-29-git-workshop#5]
We could probably remove that section too?  Though I'm kind of for leaving the lessons currently 10-13 because I think they are useful for people, so maybe we want to leave the Rstudio one too even though we won't teach it.

**Comment by elizabethmcd** [comment]
I hate git through RStudio anyways. So clunky.

**Comment by sstevens2** [comment]
@lizilla1993  did this
