### ISSUE TITLE
Remove the conflicts lesson

### ISSUE THREAD

**Issue by sstevens2** [ComBEE-UW-Madison/2017-09-29-git-workshop#6]

**Comment by sstevens2** [comment]
Decided to use add conflicts into gh-pages lesson

**Comment by sstevens2** [comment]
Will delete later

**Comment by elizabethmcd** [comment]
Integrate into intro to github pages after showing you can work directly through GitHub pages as well as through the command line.

**Comment by elizabethmcd** [comment]
Deleted for now. Will add at end after add lesson on clicking things directly in GitHub and add if I think we will have time for it.
